version: 2

python:
  install:
  - requirements: docs/requirements.txt
  - requirements: requirements.txt
  - method: pip
    path: .
    extra_requirements:
      - docs

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.10"
  jobs:
    pre_build:
    # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/_config.yml

formats:
  - pdf
  - epub
